### ISSUE TITLE
How to upsert a  field use MongoRepository?

### ISSUE THREAD

**Issue by wuyongdec** [spring-guides/gs-accessing-mongodb-data-rest#11]
In this guides,PUT, PATCH, and DELETE REST calls to either replace, update, or delete existing records.
But in the case ,if the field does not exist,insert one ;Else update the field,How to do it?

**Comment by mp911de** [comment]
Issuing a `PUT /{repository}/{id}` creates or replaces an entity.

**Comment by olivergierke** [comment]
First you have to make up your mind what kind of HTTP interaction you'd like to expose this functionality with. Then you'd write a dedicated controller that invokes said operations on the repository.

In general I think there's a bit of a mismatch of abstraction between the detailed, store-specific operations on data that you can implement in a repository and the level of abstraction that you should strive for when building REST APIs. Executing an upsert is not something I'd want to elevate into an HTTP based API. The latter is supposed to model business level interactions in which an upsert can be an implementation detail. But the latter should stay exactly that: an implementation detail.
