### ISSUE TITLE
Cannot expose resource IDs via custom RepositoryRestMvcConfiguration

### ISSUE THREAD

**Issue by jlsalmon** [spring-guides/gs-accessing-mongodb-data-rest#3]
Hi,

I'm trying to expose resource IDs in my project by using `RepositoryRestConfiguration#exposeIdsFor()`. It wasn't working in my larger application, so I came all the way back to the starter project to see if I'd messed something up somehow.

But I'm still not able to see IDs in the JSON responses with the following custom configuration:

    @Configuration
    public class CustomRepositoryRestMvcConfiguration extends SpringBootRepositoryRestMvcConfiguration {

      @Override
      protected void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
        config.exposeIdsFor(Person.class);
      }
    }

Application.java:

    @SpringBootApplication
    @Import(CustomRepositoryRestMvcConfiguration.class)
    public class Application {

      public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
      }
    }

Am I doing something obviously wrong here? All the examples I've found online indicate that this should work. Maybe I've found a regression, but I doubt it.

I hope this repo is the right place to report this issue, but apologies if it isn't.

Thanks in advance for any help!

**Comment by jlsalmon** [comment]
I thought perhaps my custom configuration wasn't being loaded somehow, but I just tested by using `RepositoryRestConfiguration#setReturnBodyOnCreate()` and it works as it should (gives me a response body after a POST). So my config is definitely being loaded.

**Comment by gregturn** [comment]
This looks like a regression of some kind. I thought it might Mongo-only (different @Id annotation), but it also fails with Spring Data JPA as well.

/cc @olivergierke

**Comment by olivergierke** [comment]
Would you mind creating a ticket with [Spring Data REST](https://jira.spring.io/browse/DATAREST) with a sample project reproducing the issue?

**Comment by jlsalmon** [comment]
@olivergierke: done: [DATAREST-501](https://jira.spring.io/browse/DATAREST-501). Thanks for the quick response :)

**Comment by olivergierke** [comment]
:+1:
